name: Bug report
description: Report a bug with the Budget Tracker project
title: "[BUG] - "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a bug report! Please provide the following details so we can address the issue.

  - type: input
    id: bug_description
    attributes:
      label: Bug Description
      description: Briefly describe the issue.
      placeholder: "What went wrong?"

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide step-by-step instructions to reproduce the bug.
      placeholder: |
        1. Step one
        2. Step two
        3. ...

  - type: input
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Expected outcome here"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the issue.
      placeholder: "Any other context or details"

