name: Documentation Update
description: Suggest or report a change in the documentation
title: "[DOC UPDATE] - "
labels: documentation
body:
  - type: markdown
    attributes:
      value: |
        Documentation is crucial for maintaining a healthy project. Please provide details for updating or improving the documentation.

  - type: input
    id: affected_section
    attributes:
      label: Affected Documentation Section
      description: Mention which part of the documentation is being updated.
      placeholder: "Where is the change needed?"

  - type: textarea
    id: new_content
    attributes:
      label: New Content or Changes
      description: Provide the new or updated content for the documentation.
      placeholder: "Describe the documentation changes you'd like to see."

  - type: input
    id: reason_for_change
    attributes:
      label: Reason for Change
      description: Explain why this documentation update is necessary.
      placeholder: "What's the reason for this update?"

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other information or references for the update.
      placeholder: "Any other details or context"
